package com.goldmansachs.elasticdatareprocessing.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionRequest;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionResult;
import com.goldmansachs.elasticdatareprocessing.model.ElasticProcessingRequest;
import org.elasticsearch.action.index.IndexRequest;
import org.elasticsearch.action.index.IndexResponse;
import org.elasticsearch.client.RequestOptions;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.client.indices.CreateIndexRequest;
import org.elasticsearch.client.indices.CreateIndexResponse;
import org.elasticsearch.client.indices.GetIndexRequest;
import org.elasticsearch.rest.RestStatus;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import jakarta.json.JsonObject;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class ElasticsearchServiceTest {

    @Mock
    private ObjectMapper objectMapper;
    
    @Mock
    private RestHighLevelClient elasticsearchClient;
    
    @Captor
    private ArgumentCaptor<IndexRequest> indexRequestCaptor;

    @InjectMocks
    private ElasticsearchService elasticsearchService;

    @Test
    void testProcessRecord() throws Exception {
    }

    @Test
    void testNormalizePath() throws Exception {
        Method normalizePathMethod = ElasticsearchService.class.getDeclaredMethod(
                "normalizePath", String.class);
        normalizePathMethod.setAccessible(true);

        assertEquals("/test/path", normalizePathMethod.invoke(elasticsearchService, "/test/path"));
        assertEquals("/test/path", normalizePathMethod.invoke(elasticsearchService, "test/path"));
    }

    @Test
    void testBuildFilterQuery() throws Exception {
    }
    
    @Test
    void testInsertDocumentWithProvidedId() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        documentData.put("field2", "value2");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("test-index")
                .documentId("test-doc-1")
                .documentData(documentData)
                .build();
        
        GetIndexRequest getIndexRequest = mock(GetIndexRequest.class);
        when(elasticsearchClient.indices().exists(any(GetIndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(true);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.status()).thenReturn(RestStatus.CREATED);
        when(indexResponse.getId()).thenReturn("test-doc-1");
        
        when(elasticsearchClient.index(any(IndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(elasticsearchClient).index(indexRequestCaptor.capture(), eq(RequestOptions.DEFAULT));
        IndexRequest capturedRequest = indexRequestCaptor.getValue();
        
        assertEquals("test-index", capturedRequest.index());
        assertEquals("test-doc-1", capturedRequest.id());
        
        assertTrue(result.isSuccessful());
        assertEquals("test-doc-1", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: test-doc-1", result.getMessage());
    }
    
    @Test
    void testInsertDocumentWithAutoGeneratedId() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        documentData.put("field2", "value2");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("test-index")
                .documentData(documentData)
                .build();
        
        when(elasticsearchClient.indices().exists(any(GetIndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(true);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.status()).thenReturn(RestStatus.CREATED);
        when(indexResponse.getId()).thenReturn("generated-id-123");
        
        when(elasticsearchClient.index(any(IndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(elasticsearchClient).index(indexRequestCaptor.capture(), eq(RequestOptions.DEFAULT));
        IndexRequest capturedRequest = indexRequestCaptor.getValue();
        
        assertEquals("test-index", capturedRequest.index());
        assertNull(capturedRequest.id()); // ID should be null for auto-generation
        
        assertTrue(result.isSuccessful());
        assertEquals("generated-id-123", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: generated-id-123", result.getMessage());
    }
    
    @Test
    void testInsertDocumentWithIndexCreation() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("new-index")
                .documentId("test-doc-1")
                .documentData(documentData)
                .build();
        
        when(elasticsearchClient.indices().exists(any(GetIndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(false);
        
        CreateIndexResponse createIndexResponse = mock(CreateIndexResponse.class);
        when(createIndexResponse.isAcknowledged()).thenReturn(true);
        
        when(elasticsearchClient.indices().create(any(CreateIndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(createIndexResponse);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.status()).thenReturn(RestStatus.CREATED);
        when(indexResponse.getId()).thenReturn("test-doc-1");
        
        when(elasticsearchClient.index(any(IndexRequest.class), eq(RequestOptions.DEFAULT)))
                .thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(elasticsearchClient.indices()).create(any(CreateIndexRequest.class), eq(RequestOptions.DEFAULT));
        verify(elasticsearchClient).index(any(IndexRequest.class), eq(RequestOptions.DEFAULT));
        
        assertTrue(result.isSuccessful());
        assertEquals("test-doc-1", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: test-doc-1", result.getMessage());
    }
}
