package com.goldmansachs.elasticdatareprocessing.service;

import co.elastic.clients.elasticsearch.ElasticsearchClient;
import co.elastic.clients.elasticsearch._types.Result;
import co.elastic.clients.elasticsearch.core.IndexResponse;
import co.elastic.clients.elasticsearch.indices.CreateIndexResponse;
import co.elastic.clients.elasticsearch.indices.ExistsRequest;
import co.elastic.clients.elasticsearch.indices.BooleanResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionRequest;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class ElasticsearchServiceTest {

    @Mock
    private ObjectMapper objectMapper;
    
    @Mock
    private ElasticsearchClient elasticsearchClient;

    @InjectMocks
    private ElasticsearchService elasticsearchService;

    @Test
    void testProcessRecord() throws Exception {
    }

    @Test
    void testNormalizePath() throws Exception {
        Method normalizePathMethod = ElasticsearchService.class.getDeclaredMethod(
                "normalizePath", String.class);
        normalizePathMethod.setAccessible(true);

        assertEquals("/test/path", normalizePathMethod.invoke(elasticsearchService, "/test/path"));
        assertEquals("/test/path", normalizePathMethod.invoke(elasticsearchService, "test/path"));
    }

    @Test
    void testBuildFilterQuery() throws Exception {
    }
    
    @Test
    void testInsertDocumentWithProvidedId() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        documentData.put("field2", "value2");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("test-index")
                .documentId("test-doc-1")
                .documentData(documentData)
                .build();
        
        co.elastic.clients.elasticsearch.indices.IndicesClient indicesClient = mock(co.elastic.clients.elasticsearch.indices.IndicesClient.class);
        when(elasticsearchClient.indices()).thenReturn(indicesClient);
        
        BooleanResponse existsResponse = mock(BooleanResponse.class);
        when(existsResponse.value()).thenReturn(true);
        when(indicesClient.exists(any(Function.class))).thenReturn(existsResponse);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.result()).thenReturn(Result.Created);
        when(indexResponse.id()).thenReturn("test-doc-1");
        
        when(elasticsearchClient.index(any(Function.class))).thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(elasticsearchClient).index(any(Function.class));
        
        assertTrue(result.isSuccessful());
        assertEquals("test-doc-1", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: test-doc-1", result.getMessage());
    }
    
    @Test
    void testInsertDocumentWithAutoGeneratedId() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        documentData.put("field2", "value2");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("test-index")
                .documentData(documentData)
                .build();
        
        co.elastic.clients.elasticsearch.indices.IndicesClient indicesClient = mock(co.elastic.clients.elasticsearch.indices.IndicesClient.class);
        when(elasticsearchClient.indices()).thenReturn(indicesClient);
        
        BooleanResponse existsResponse = mock(BooleanResponse.class);
        when(existsResponse.value()).thenReturn(true);
        when(indicesClient.exists(any(Function.class))).thenReturn(existsResponse);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.result()).thenReturn(Result.Created);
        when(indexResponse.id()).thenReturn("generated-id-123");
        
        when(elasticsearchClient.index(any(Function.class))).thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(elasticsearchClient).index(any(Function.class));
        
        assertTrue(result.isSuccessful());
        assertEquals("generated-id-123", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: generated-id-123", result.getMessage());
    }
    
    @Test
    void testInsertDocumentWithIndexCreation() throws Exception {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "value1");
        
        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("new-index")
                .documentId("test-doc-1")
                .documentData(documentData)
                .build();
        
        co.elastic.clients.elasticsearch.indices.IndicesClient indicesClient = mock(co.elastic.clients.elasticsearch.indices.IndicesClient.class);
        when(elasticsearchClient.indices()).thenReturn(indicesClient);
        
        BooleanResponse existsResponse = mock(BooleanResponse.class);
        when(existsResponse.value()).thenReturn(false);
        when(indicesClient.exists(any(Function.class))).thenReturn(existsResponse);
        
        CreateIndexResponse createIndexResponse = mock(CreateIndexResponse.class);
        when(createIndexResponse.acknowledged()).thenReturn(true);
        when(indicesClient.create(any(Function.class))).thenReturn(createIndexResponse);
        
        IndexResponse indexResponse = mock(IndexResponse.class);
        when(indexResponse.result()).thenReturn(Result.Created);
        when(indexResponse.id()).thenReturn("test-doc-1");
        
        when(elasticsearchClient.index(any(Function.class))).thenReturn(indexResponse);
        
        DataInsertionResult result = elasticsearchService.insertDocument(request);
        
        verify(indicesClient).create(any(Function.class));
        verify(elasticsearchClient).index(any(Function.class));
        
        assertTrue(result.isSuccessful());
        assertEquals("test-doc-1", result.getDocumentId());
        assertEquals(documentData, result.getDocumentData());
        assertEquals("Document successfully inserted with ID: test-doc-1", result.getMessage());
    }
}
