package com.goldmansachs.elasticdatareprocessing.functional;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionRequest;
import com.goldmansachs.elasticdatareprocessing.model.DataInsertionResult;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Functional tests for the data insertion workflow.
 * Tests the complete end-to-end flow from API request to Elasticsearch insertion.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
public class ElasticDataInsertionFunctionalTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void testInsertDocumentWorkflow() {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "functional-test-value");
        documentData.put("field2", 123);
        documentData.put("nested", Map.of("field3", "nested-value"));

        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("functional-test-index")
                .documentId("functional-test-doc-1")
                .documentData(documentData)
                .build();

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<DataInsertionRequest> requestEntity = new HttpEntity<>(request, headers);

        ResponseEntity<DataInsertionResult> responseEntity = restTemplate.postForEntity(
                "/api/elastic/insert",
                requestEntity,
                DataInsertionResult.class);

        assertEquals(200, responseEntity.getStatusCodeValue(), "Response status code should be 200 OK");
        
        DataInsertionResult result = responseEntity.getBody();
        assertNotNull(result, "Response body should not be null");
        assertTrue(result.isSuccessful(), "Insertion should be successful");
        assertEquals("functional-test-doc-1", result.getDocumentId(), "Document ID should match the requested ID");
        assertEquals(documentData, result.getDocumentData(), "Document data should match the requested data");
        assertTrue(result.getMessage().contains("functional-test-doc-1"), "Message should contain the document ID");

        Map<String, String> urlVariables = new HashMap<>();
        urlVariables.put("index", "functional-test-index");
        urlVariables.put("id", "functional-test-doc-1");

        ResponseEntity<String> verificationResponse = restTemplate.getForEntity(
                "/api/elastic/document/{index}/{id}",
                String.class,
                urlVariables);

        assertEquals(200, verificationResponse.getStatusCodeValue(), 
                "Verification response status code should be 200 OK");
        assertNotNull(verificationResponse.getBody(), 
                "Verification response body should not be null");
        assertTrue(verificationResponse.getBody().contains("functional-test-value"), 
                "Verification response should contain the document data");
    }

    @Test
    void testInsertDocumentWithAutoGeneratedId() {
        Map<String, Object> documentData = new HashMap<>();
        documentData.put("field1", "auto-id-test-value");
        documentData.put("timestamp", System.currentTimeMillis());

        DataInsertionRequest request = DataInsertionRequest.builder()
                .indexName("functional-test-index")
                .documentData(documentData)
                .build();

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<DataInsertionRequest> requestEntity = new HttpEntity<>(request, headers);

        ResponseEntity<DataInsertionResult> responseEntity = restTemplate.postForEntity(
                "/api/elastic/insert",
                requestEntity,
                DataInsertionResult.class);

        assertEquals(200, responseEntity.getStatusCodeValue(), "Response status code should be 200 OK");
        
        DataInsertionResult result = responseEntity.getBody();
        assertNotNull(result, "Response body should not be null");
        assertTrue(result.isSuccessful(), "Insertion should be successful");
        assertNotNull(result.getDocumentId(), "Document ID should be auto-generated and not null");
        assertEquals(documentData, result.getDocumentData(), "Document data should match the requested data");
        assertTrue(result.getMessage().contains("successfully inserted"), 
                "Message should indicate successful insertion");
    }
}
